name: letsgpt
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  dio: ^5.1.2
  flutter_app_name: ^0.1.0
  get: ^4.6.5
  animations: ^2.0.1
  lottie: ^1.1.0
  flutter_screenutil: ^5.0.0+2
  fluro: ^2.0.3
  transparent_image: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  animated_text_kit: ^4.2.2
  flutter_chat_bubble: ^2.0.2


flutter_app_name:
  name: "随时GPT"

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true
  assets:
    - assets/images/
    - assets/Mobilo/
    - assets/status/

